Week10/CodiceFiscale/CodiceFiscale/Controllers/CFController.cs
using BusinessLogic;
using DataLayer;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Http;
using NuGet.Protocol;

namespace CodiceFiscale.Controllers;

public class CFController : Controller
{
    
    private readonly ICodiceFiscale _calcolo;
    private readonly ComuniContext _comuni;

    public CFController(ICodiceFiscale codice, ComuniContext comuni)
    {
        _calcolo = codice;
        _comuni = comuni;
    }

    public async Task<IActionResult> Index()
    {
   
        var x = new PersonaDataViewModel() { CodiceFiscale=""};
   
        return View("Index",x);

    }

    [HttpPost]
    public async Task<IActionResult> Index(PersonaDataViewModel x)
    {
        if (ModelState.IsValid) { 
        try
        {
            
            x.Istat = _comuni.Comunis.FirstOrDefault(y => y.Comune == x.Istat).Code;
            x.CodiceFiscale = _calcolo.CalcolaCodiceFiscale(x);
        }catch(Exception e) { return RedirectToAction("Index"); }
		}
		return View("Index", x);
    }



    public async Task<IActionResult> CodiceFiscale(PersonaDataViewModel x)
    {
        try
        {
            x.Istat = _comuni.Comunis.FirstOrDefault(y => y.Comune == x.Istat).Code;
        }
        catch (Exception e) { BadRequest(); }       
        var codice= _calcolo.CalcolaCodiceFiscale(x).ToJson();
        return Ok(codice);

    }


    public async Task<IActionResult> GetComuni(string? id)
    {
        List<Comuni> comuni = new();

        if (!string.IsNullOrEmpty(id))
        {
               comuni = await _comuni.Comunis.Where(x => x.Sigla == id).ToListAsync();
        }
        else
        {
            comuni = await _comuni.Comunis.ToListAsync();
        }
     

        return  Ok(comuni);
    }


    


}

Week10/CodiceFiscale/CodiceFiscale/Controllers/ComunisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace CodiceFiscale.Controllers
{
	[Authorize(Roles = "SuperAdmin")]
	public class ComunisController : Controller
    {
        private readonly ComuniContext _context;

        public ComunisController(ComuniContext context)
        {
            _context = context;
        }
        
        // GET: Comunis
        public async Task<IActionResult> Index()
        {
              return _context.Comunis != null ? 
                          View(await _context.Comunis.ToListAsync()) :
                          Problem("Entity set 'ComuniContext.Comunis'  is null.");
        }

        // GET: Comunis/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Comunis == null)
            {
                return NotFound();
            }

            var comuni = await _context.Comunis
                .FirstOrDefaultAsync(m => m.Code == id);
            if (comuni == null)
            {
                return NotFound();
            }

            return View(comuni);
        }

        // GET: Comunis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Comunis/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Comune,Regione,Provincia,Sigla,Code")] Comuni comuni)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comuni);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(comuni);
        }

        // GET: Comunis/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Comunis == null)
            {
                return NotFound();
            }

            var comuni = await _context.Comunis.FindAsync(id);
            if (comuni == null)
            {
                return NotFound();
            }
            return View(comuni);
        }

        // POST: Comunis/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Comune,Regione,Provincia,Sigla,Code")] Comuni comuni)
        {
            if (id != comuni.Code)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comuni);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComuniExists(comuni.Code))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comuni);
        }

        // GET: Comunis/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Comunis == null)
            {
                return NotFound();
            }

            var comuni = await _context.Comunis
                .FirstOrDefaultAsync(m => m.Code == id);
            if (comuni == null)
            {
                return NotFound();
            }

            return View(comuni);
        }

        // POST: Comunis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Comunis == null)
            {
                return Problem("Entity set 'ComuniContext.Comunis'  is null.");
            }
            var comuni = await _context.Comunis.FindAsync(id);
            if (comuni != null)
            {
                _context.Comunis.Remove(comuni);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComuniExists(string id)
        {
          return (_context.Comunis?.Any(e => e.Code == id)).GetValueOrDefault();
        }
    }
}

Week10/CodiceFiscale/CodiceFiscale/Controllers/UserController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace CodiceFiscale.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _user;
        private readonly RoleManager<IdentityRole> _role;

        public UserController(UserManager<IdentityUser> user, RoleManager<IdentityRole> role) {

            _user = user;
            _role = role;
        }


        public IActionResult Index()
        {
            var user = _user.Users;
            return View(user);

        }
 

        public IActionResult EditUser(string id)
        {
            var user = _user.Users.FirstOrDefault(x => x.Id == id);
       
            return View(user);
        }

       
        [HttpPost]
        public async Task<IActionResult> EditUser(string id, string permission)
        {
            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.AddToRoleAsync(user, permission);
            return RedirectToAction("EditUser", new { user.Id });
        }


        public async Task<IActionResult> DeleteUser(string id)
        {

            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.DeleteAsync(user);

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> RemoveRole(string role, string id)
        {

            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.RemoveFromRoleAsync(user, role);

            return RedirectToAction("EditUser" ,new { id });
        }
    }



    
}

Week10/CodiceFiscale/CodiceFiscale/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject RoleManager<IdentityRole> role
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodiceFiscale</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodiceFiscale.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="CF" asp-action="Index">CodiceFiscale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CF" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("SuperAdmin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Comunis" asp-action="Index">Comuni</a>
                            </li>
                        }
                    </ul>
                    @if (SignInManager.IsSignedIn(User) &&  User.IsInRole("SuperAdmin"))
                    {
                     
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AppRoles" asp-action="Index">Permission</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div role="main" class="pb-3" style="margin-left:15px;">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CodiceFiscale - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
  
</body>
</html>