Week9/PizzeriaWebApp/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PizzeriaWebApp.DataLayer;
using PizzeriaWebApp.Models;

namespace PizzeriaWebApp.Controllers
{//devo poter associare un utente a un ruolo ben preciso

	[Authorize(Roles = "admin")]
	public class RolesController : Controller
	{
		private readonly ApplicationDbContext _context = new ApplicationDbContext();
		// GET: Role
		public ActionResult Index()
		{
			var users = _context.Users.Select(x => new UserViewModel
			{
				Id = x.Id,
				Name = x.UserName
			});

			var model = new RolesIndexviewModel
			{

				Users =users
			};
			return View(model);
		}
		public ActionResult Edit(string id)
		{
			var user = _context.Users.Single(u => u.Id == id);
			var roles = _context.Roles.OrderBy(x => x.Name).ToList();
			//dato id ruolo,recupero il nome

			var userRoles = user.Roles.Select(r => roles.Single(e => r.RoleId == e.Id).Name);
			var model = new RoleEditViewModel
			{
				User = new UserViewModel { Id = id, Name = user.UserName, Roles = userRoles },
				Roles = roles.Select(r => r.Name)

			};
			return View(model);
		}


	}
}

Week9/PizzeriaWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm  colorebox">
        <div class="container ">
            @Html.ActionLink("Il Forno", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Carrello", "Index", "Carrello", new { area = "" }, new { @class = "nav-link" })</li>



                    @if (User.IsInRole("admin"))

                    {   <li>@Html.ActionLink("Ordini", "Ordini", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Admin", "Gestione", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        @*<li>@Html.ActionLink("Ruoli", "Index", "Roles", new { area = "" }, new { @class = "nav-link" })</li>*@
                    }
                </ul>
                @Html.Partial("_LoginPartial")
                </div>
            </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Il Forno</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>